version: "3"


services:
  postgres:
    image: postgres:13
    restart: always
    ports:
    - 127.0.0.1:5432:5432
    environment:
      POSTGRES_DB: hastur
      POSTGRES_USER: hastur
      POSTGRES_PASSWORD: hastur
    volumes:
      - data-volumes:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 5000:8080

volumes:
  data-volumes:
